// Generated by jextract

package eu.jameshamilton.llvm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef uint8_t *(*LLVMMemoryManagerAllocateCodeSectionCallback)(void *, uintptr_t, unsigned int, unsigned int, const char *)
 * }
 */
public class LLVMMemoryManagerAllocateCodeSectionCallback {

    LLVMMemoryManagerAllocateCodeSectionCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment Opaque, long Size, int Alignment, int SectionID, MemorySegment SectionName);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        LLVM.C_POINTER,
        LLVM.C_POINTER,
        LLVM.C_LONG,
        LLVM.C_INT,
        LLVM.C_INT,
        LLVM.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = LLVM.upcallHandle(LLVMMemoryManagerAllocateCodeSectionCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(LLVMMemoryManagerAllocateCodeSectionCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment Opaque, long Size, int Alignment, int SectionID, MemorySegment SectionName) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, Opaque, Size, Alignment, SectionID, SectionName);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

